# Generated by Django 4.1.7 on 2023-02-16 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruso', models.CharField(max_length=100, verbose_name='curso')),
                ('letra', models.TextField(max_length=10, verbose_name='letra')),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
                ('numAlumnos', models.IntegerField(verbose_name='Numero de Alumnos')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='ubicacion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('correo', models.EmailField(max_length=200, null=True, verbose_name='correo')),
                ('asignatura', models.CharField(max_length=200, verbose_name='asignatura')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('grupos', models.ManyToManyField(to='principal.grupos', verbose_name='grupos')),
            ],
            options={
                'verbose_name': 'profesor',
                'verbose_name_plural': 'profesores',
                'ordering': ['-created'],
            },
        ),
    ]
