# Generated by Django 4.1.7 on 2023-02-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupos',
            old_name='cruso',
            new_name='curso',
        ),
    ]
