# Generated by Django 4.1.5 on 2023-01-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositos', '0002_rename_compras_propositos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propositos',
            old_name='conseguido',
            new_name='conseg',
        ),
        migrations.RenameField(
            model_name='propositos',
            old_name='fechaConseguido',
            new_name='fecConseg',
        ),
        migrations.RenameField(
            model_name='propositos',
            old_name='fechaObjetivo',
            new_name='fecObj',
        ),
        migrations.RenameField(
            model_name='propositos',
            old_name='proposito',
            new_name='prop',
        ),
    ]
